### PR TITLE
Port musicutils.py to Typescript

### PR DESCRIPTION
**Pull request by daksh4469**
## Description:
Issue Reference: #18 
- Adds the interface `IMusicutils` in `musicutils.d.ts`
- Adds the implementation of Musicutils class in `musicutils.ts`
- Adds the unit tests to test the methods of Musicutils class in `musicutils.test.ts`

## Test Verification:
Screenshot from 2021-03-20 16-38-45

Please share your feedback @meganindya.
Thanks.

### CODE REVIEW

**Review by meganindya — COMMENTED** [review]
This is a utilities file. It was meant to contain constants and functions at the top level. To enforce scoping when importing as a module to other modules, `import * as Utils from './musicutils';` followed by usage such as `Utils.foo`, `Utils.bar` can be performed.

Changing the structure wasn't required. And please stick to the code quality conventions. I'll do the upward work required on this branch and merge this.

**Comment by daksh4469** [comment]
Thanks for your feedback @meganindya.
Can you please specify where can I improve code quality so that I can follow the conventions more precisely the next time?

**Comment by meganindya** [comment]
see root README

**Comment by daksh4469** [comment]
Got it! Thanks :)

**Comment by daksh4469** [comment]
I understand what you are specifying about keeping the functions and constants at the top level and not making a `class` for them so that they could be imported further. Apologies from my side. Will do better next time.
Thanks.

**Comment by ksraj123** [comment]
This is already halfway done in #23 and other PRs. Every PR does the part of musicutils it needs, so the functionality of that part of musicutils code in ensured in same PR where it's being used. We could do the test cases for what's left at the end. I think merging this PR would create conflicts for others. Thanks cc - @meganindya

**Comment by meganindya** [comment]
Oh I didn't realise that. Since this PR completed the port I modified and merged it in #28. Very sorry.

Please pick up from there. That file is completely ported.

**Pull request closed without merging**
