### PR TITLE
Temperament - port to TypeScript

### PR DESCRIPTION
**Pull request by ksraj123**
@meganindya I have tried to incoporate the comments on my previous PR and elsewhere into this one. Could you please have a look? I have ported a smaller file `temperament.py` entirely with its testcases and some parts of `musicutils.py` which were being utilised by this file. All the test cases seem to pass.

Screenshot 2021-03-17 at 10 07 29 PM

Please share feedback and suggestions. Thanks

### CODE REVIEW

**Review by meganindya — COMMENTED** [review]
This is totally in line with what I was thinking.

I've been a little busy; let me get back to you and work on how we can proceed hereafter.

Good work!

**Comment by meganindya** [comment]
BTW, please adhere to [these](https://github.com/sugarlabs/musicblocks-v4-lib#code-quality-notes).

One tip: you can use a path pattern like `npm run test -- src/.prototype/musicutils` which will only run tests that start with the provided path.

**Review by meganindya — CHANGES_REQUESTED** [review]
The file organisation needs to change. Please do the following:

- Create a `dummy` branch on top of the current HEAD of `musicutils`
- (This branch must be on you local)
- Checkout `dummy` and cherry pick this commit (don't commit immediately)
- We have the fully implemented `musicutils.ts` so remove `MusicUtils.ts`
- Put `temperament.d.ts` inside `src/.prototype/musicutils/ts/@types/`
- Rename `Temperament.ts` to `temperament.ts` and `Temperament.test.ts` to `temperament.test.ts` (I carelessly mentioned it as _PascalCase_ in the docs instead of _camelCase_)
- Commit in `dummy`, the `.d.ts` and `.ts` file.
- Commit in `dummy` the `.test.ts` file.
- Add description in the commits if there's something you need to mention.
- Hard reset `18-port....` to HEAD of `dummy`
- Delete `dummy`
- Force push the branch to upstream (here)
- Change the PR target to `musicutils` instead of `develop`

The code should be good enough. I'll do a check after.

**Comment by ksraj123** [comment]
@meganindya Thank you for laying out the required changes and detailed steps to do them. The changes have been made. Please have a look, Thanks.

**Review by meganindya — APPROVED** [review]
Seems to be fine. I want to add some minor refactoring &mdash; mostly cosmetic changes. I'll add them in this branch and merge this. Converting to draft for now to avoid confusion.

**Comment by meganindya** [comment]
How far are you with the other file &mdash; `key signature.py`?

**Comment by ksraj123** [comment]
@meganindya almost done with `keysingature.py` as well. Will open a PR by tomorrow morning.

**Comment by meganindya** [comment]
Alright I'll get it done tonight.

**Review by meganindya — APPROVED** [review]

**Comment by meganindya** [comment]
Addresses #18.

**Pull request merged**
