### PR TITLE
Example section of musicutils/readme updated

### PR DESCRIPTION
**Pull request by KaranSingh1301**

### CODE REVIEW

**Comment by KaranSingh1301** [comment]
Anyone please suggest me how to remove these linting errors. I have seen the logs it is generating error from those files which I haven't updated.

thanks.

**Comment by meganindya** [comment]
The CI workflows shouldn't even trigger on this branch. Did you update the target from `develop` to `musicutils`. Would make sense in that case.

**Review by meganindya — COMMENTED** [review]
This isn't addressing the issue according to the requirements specified there.

**Comment by meganindya** [comment]
Please follow all of these &mdash; https://github.com/sugarlabs/musicblocks-v4-lib#code-quality-notes.

**Comment by KaranSingh1301** [comment]
@meganindya sir as mention in issue #30 there's one section of example  in READme, I have updated the same. Please Guide me through the mistake I have made.

**Pull request closed without merging**
