### PR TITLE
Operations and tests on string

### PR DESCRIPTION
**Pull request by ricknjacky**
issue reference:- #6 

I have added operations, please review @meganindya

### CODE REVIEW

**Comment by ricknjacky** [comment]
Screenshot (560)


All tests cases pass

**Comment by ricknjacky** [comment]
@meganindya any feedback/suggestions for this PR?

**Comment by meganindya** [comment]
I want to make some changes to the primitive types ... will do a rain check

**Comment by ricknjacky** [comment]
> I want to make some changes to the primitive types ... will do a rain check

Ok 👍 looking forward to it.

**Review by meganindya — APPROVED** [review]

**Pull request merged**
