### PR TITLE
Reorganization

### PR DESCRIPTION
**Pull request by walterbender**
Three changes in separate commits:
(1) Support for octave ratio added to Temperament code
(2) Break up of unittests into more fine-grained tests: from 5 to 33.
(3) Refactoring of scale and key signature code such that much of the complexity of managing alternative naming schemes is moved to scale.py. (This could go even further if we move the closest note code into scale, which in retrospect is where it belongs.)

### CODE REVIEW

**Comment by walterbender** [comment]
Let me make the suggested change above before we merge this.

**Comment by meganindya** [comment]
Would you also make the changes in the TypeScript files or we do that after, in a separate PR?

**Comment by walterbender** [comment]
Let's do typescript as a separate commit. Should be easier once the Python code is stable.

**Comment by walterbender** [comment]
I think this is in decent shape now. To summarize:
(1) Added support for Octave Ratio
(2) Moved much of the functionality found in key signature into the scale class. (These methods all depend upon scale, not key signature, so it is a more appropriate place for them. Key signature now is really just for defining key and mode (and fixed/movable) and subsequently redefining the scale, which handles everything else.)
(3) Better organization and clean up of the unit tests.
(4) Clean up of the current note code to reflect the above.
(5) Clean up of the README to reflect the above.

**Comment by walterbender** [comment]
I'll work on the Typescript code in a separate PR

**Pull request closed without merging**
